# Generated by Django 2.2.1 on 2019-05-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Distribuidores')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion_Bancaria',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=100, unique=True, verbose_name='Bancos')),
            ],
        ),
        migrations.CreateModel(
            name='Chequera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Cheque', models.CharField(max_length=10, verbose_name='Cheque No.')),
                ('total', models.CharField(max_length=15, verbose_name='Total')),
                ('fecha_creado', models.DateField(verbose_name='Fecha de elaboracion')),
                ('fecha_pago', models.DateField(verbose_name='Fecha a Pagar')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('imge_cheque', models.ImageField(upload_to='cheque/pictures')),
                ('cuenta_bancaria', models.CharField(max_length=30, verbose_name='Cuenta Bancaria')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.Distribuidor')),
                ('institucion_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.Institucion_Bancaria')),
            ],
        ),
    ]
