# Generated by Django 2.2.1 on 2019-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequera',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de elaboracion'),
        ),
    ]
