# Generated by Django 2.2.1 on 2019-05-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_auto_20190521_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=20, unique=True, verbose_name='No. Cuenta')),
                ('titular', models.CharField(max_length=100, verbose_name='Titular')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.Institucion_Bancaria')),
            ],
        ),
    ]
