# Generated by Django 2.2.1 on 2019-05-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_cuentasbancarias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequera',
            name='institucion_bancaria',
        ),
    ]
