# Generated by Django 2.2.1 on 2019-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_auto_20190522_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequera',
            name='id',
        ),
        migrations.AddField(
            model_name='chequera',
            name='id_chequera',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
