# Generated by Django 2.2.1 on 2019-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_auto_20190522_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequera',
            name='fecha_pago',
            field=models.DateField(blank=True, verbose_name='Fecha a Pagar'),
        ),
    ]
