# Generated by Django 2.2.1 on 2019-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_auto_20190522_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequera',
            name='imge_cheque',
            field=models.ImageField(upload_to='cheques/pictures'),
        ),
    ]
